/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  trailsSidebar: [
    { type: "doc", id: "trails/intro", label: "Intro" },
    {
      type: 'category',
      label: 'Prague Trails',
      collapsed: false,
      link: { type: 'doc', id: 'trails/prague' },
      items: [
        {
          type: 'autogenerated',
          dirName:   'trails/prague',
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Central Bohemia Trails',
    //   link: { type: 'doc', id: 'trails/central-bohemia' },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName:   'trails/central-bohemia',
    //     },
    //   ],
    // },
  ],
  mapsSidebar: [
    { type: "doc", id: "maps/prague-trails", label: "Prague Trails" },
    { type: "doc", id: "maps/prague-public-transport", label: "Prague Public Transport" },
    { type: "doc", id: "maps/trains", label: "Trains" },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
